# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_datatype_editor.ui'
#
# Created: Wed May 25 22:56:28 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DataTypeEditorDialog(object):
    def setupUi(self, DataTypeEditorDialog):
        DataTypeEditorDialog.setObjectName(_fromUtf8("DataTypeEditorDialog"))
        DataTypeEditorDialog.resize(360, 446)
        self.verticalLayout = QtGui.QVBoxLayout(DataTypeEditorDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cmbDatatype = QtGui.QComboBox(DataTypeEditorDialog)
        self.cmbDatatype.setObjectName(_fromUtf8("cmbDatatype"))
        self.verticalLayout.addWidget(self.cmbDatatype)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnNew = QtGui.QPushButton(DataTypeEditorDialog)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.horizontalLayout.addWidget(self.btnNew)
        self.btnRemove = QtGui.QPushButton(DataTypeEditorDialog)
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.horizontalLayout.addWidget(self.btnRemove)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtGui.QGroupBox(DataTypeEditorDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.leName = QtGui.QLineEdit(self.groupBox)
        self.leName.setObjectName(_fromUtf8("leName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.leName)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cmbType = QtGui.QComboBox(self.groupBox)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmbType)
        self.spatialAccuracyLabel = QtGui.QLabel(self.groupBox)
        self.spatialAccuracyLabel.setObjectName(_fromUtf8("spatialAccuracyLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.spatialAccuracyLabel)
        self.leSpatialAccuracy = QtGui.QLineEdit(self.groupBox)
        self.leSpatialAccuracy.setObjectName(_fromUtf8("leSpatialAccuracy"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.leSpatialAccuracy)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.textThematicAccuracy = QtGui.QTextEdit(self.groupBox)
        self.textThematicAccuracy.setObjectName(_fromUtf8("textThematicAccuracy"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.textThematicAccuracy)
        self.leSpatialScale = QtGui.QLineEdit(self.groupBox)
        self.leSpatialScale.setObjectName(_fromUtf8("leSpatialScale"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.leSpatialScale)
        self.spatialScaleLabel = QtGui.QLabel(self.groupBox)
        self.spatialScaleLabel.setObjectName(_fromUtf8("spatialScaleLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.spatialScaleLabel)
        self.thematicContentLabel = QtGui.QLabel(self.groupBox)
        self.thematicContentLabel.setObjectName(_fromUtf8("thematicContentLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.thematicContentLabel)
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lstKeywords = QtGui.QListWidget(self.frame)
        self.lstKeywords.setObjectName(_fromUtf8("lstKeywords"))
        self.gridLayout.addWidget(self.lstKeywords, 0, 0, 1, 3)
        self.btnAddKeyword = QtGui.QPushButton(self.frame)
        self.btnAddKeyword.setObjectName(_fromUtf8("btnAddKeyword"))
        self.gridLayout.addWidget(self.btnAddKeyword, 1, 0, 1, 1)
        self.btnRemoveKeyword = QtGui.QPushButton(self.frame)
        self.btnRemoveKeyword.setObjectName(_fromUtf8("btnRemoveKeyword"))
        self.gridLayout.addWidget(self.btnRemoveKeyword, 1, 2, 1, 1)
        self.btnEditKeyword = QtGui.QPushButton(self.frame)
        self.btnEditKeyword.setObjectName(_fromUtf8("btnEditKeyword"))
        self.gridLayout.addWidget(self.btnEditKeyword, 1, 1, 1, 1)
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.frame)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(DataTypeEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DataTypeEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DataTypeEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DataTypeEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DataTypeEditorDialog)

    def retranslateUi(self, DataTypeEditorDialog):
        DataTypeEditorDialog.setWindowTitle(QtGui.QApplication.translate("DataTypeEditorDialog", "Manage data types", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemove.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DataTypeEditorDialog", "Type of data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.spatialAccuracyLabel.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Spatial accuracy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Thematic accuracy", None, QtGui.QApplication.UnicodeUTF8))
        self.spatialScaleLabel.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Spatial scale", None, QtGui.QApplication.UnicodeUTF8))
        self.thematicContentLabel.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Thematic content", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddKeyword.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveKeyword.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEditKeyword.setText(QtGui.QApplication.translate("DataTypeEditorDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))

