# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_metadata_browser.ui'
#
# Created: Wed May 18 16:26:01 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MetadataBrowser(object):
    def setupUi(self, MetadataBrowser):
        MetadataBrowser.setObjectName(_fromUtf8("MetadataBrowser"))
        MetadataBrowser.resize(740, 734)
        self.verticalLayout = QtGui.QVBoxLayout(MetadataBrowser)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(MetadataBrowser)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabSearch)
        self.verticalLayout_2.setMargin(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbCondition = QtGui.QGroupBox(self.tabSearch)
        self.gbCondition.setObjectName(_fromUtf8("gbCondition"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbCondition)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ledCondition = QtGui.QLineEdit(self.gbCondition)
        self.ledCondition.setObjectName(_fromUtf8("ledCondition"))
        self.horizontalLayout.addWidget(self.ledCondition)
        self.btnSearch = QtGui.QPushButton(self.gbCondition)
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.horizontalLayout.addWidget(self.btnSearch)
        self.verticalLayout_2.addWidget(self.gbCondition)
        self.gbSearch = QtGui.QGroupBox(self.tabSearch)
        self.gbSearch.setObjectName(_fromUtf8("gbSearch"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbSearch)
        self.verticalLayout_4.setMargin(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.gbSearch)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.lstResult = QtGui.QListWidget(self.splitter)
        self.lstResult.setObjectName(_fromUtf8("lstResult"))
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.wvResult = QtWebKit.QWebView(self.frame)
        self.wvResult.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.wvResult.setObjectName(_fromUtf8("wvResult"))
        self.verticalLayout_3.addWidget(self.wvResult)
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.gbSearch)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.tabCatalog = QtGui.QWidget()
        self.tabCatalog.setObjectName(_fromUtf8("tabCatalog"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabCatalog)
        self.verticalLayout_7.setMargin(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.tabCatalog)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.lstCatalog = QtGui.QListWidget(self.splitter_2)
        self.lstCatalog.setObjectName(_fromUtf8("lstCatalog"))
        self.frame_2 = QtGui.QFrame(self.splitter_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.wvCatalog = QtWebKit.QWebView(self.frame_2)
        self.wvCatalog.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.wvCatalog.setObjectName(_fromUtf8("wvCatalog"))
        self.verticalLayout_6.addWidget(self.wvCatalog)
        self.verticalLayout_7.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tabCatalog, _fromUtf8(""))
        self.tabDatabases = QtGui.QWidget()
        self.tabDatabases.setObjectName(_fromUtf8("tabDatabases"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabDatabases)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setMargin(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lstDb = QtGui.QListWidget(self.tabDatabases)
        self.lstDb.setObjectName(_fromUtf8("lstDb"))
        self.verticalLayout_5.addWidget(self.lstDb)
        self.frame_4 = QtGui.QFrame(self.tabDatabases)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnApply = QtGui.QPushButton(self.frame_4)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.horizontalLayout_2.addWidget(self.btnApply)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tabDatabases, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(MetadataBrowser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MetadataBrowser)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MetadataBrowser.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MetadataBrowser.reject)
        QtCore.QMetaObject.connectSlotsByName(MetadataBrowser)

    def retranslateUi(self, MetadataBrowser):
        MetadataBrowser.setWindowTitle(QtGui.QApplication.translate("MetadataBrowser", "Metadata browser", None, QtGui.QApplication.UnicodeUTF8))
        self.gbCondition.setTitle(QtGui.QApplication.translate("MetadataBrowser", "Search condition", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearch.setText(QtGui.QApplication.translate("MetadataBrowser", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.gbSearch.setTitle(QtGui.QApplication.translate("MetadataBrowser", "Search result", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), QtGui.QApplication.translate("MetadataBrowser", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCatalog), QtGui.QApplication.translate("MetadataBrowser", "Catalog", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApply.setText(QtGui.QApplication.translate("MetadataBrowser", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDatabases), QtGui.QApplication.translate("MetadataBrowser", "Databases", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
