# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_organization_editor.ui'
#
# Created: Wed Mar 30 23:39:19 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_OrganizationEditorDialog(object):
    def setupUi(self, OrganizationEditorDialog):
        OrganizationEditorDialog.setObjectName("OrganizationEditorDialog")
        OrganizationEditorDialog.resize(346, 598)
        self.gridLayout = QtGui.QGridLayout(OrganizationEditorDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.orgComboBox = QtGui.QComboBox(OrganizationEditorDialog)
        self.orgComboBox.setObjectName("orgComboBox")
        self.gridLayout.addWidget(self.orgComboBox, 0, 0, 1, 2)
        self.addButton = QtGui.QPushButton(OrganizationEditorDialog)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 1, 0, 1, 1)
        self.removeButton = QtGui.QPushButton(OrganizationEditorDialog)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 1, 1, 1, 1)
        self.orgGroupBox = QtGui.QGroupBox(OrganizationEditorDialog)
        self.orgGroupBox.setObjectName("orgGroupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.orgGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nameLineEdit = QtGui.QLineEdit(self.orgGroupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout_3.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.nameLabel = QtGui.QLabel(self.orgGroupBox)
        self.nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_3.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.orgButtonBox = QtGui.QDialogButtonBox(self.orgGroupBox)
        self.orgButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.orgButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.orgButtonBox.setObjectName("orgButtonBox")
        self.gridLayout_3.addWidget(self.orgButtonBox, 5, 0, 1, 2)
        self.addressGroupBox = QtGui.QGroupBox(self.orgGroupBox)
        self.addressGroupBox.setObjectName("addressGroupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.addressGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.addressGroupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.addressGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.cityLineEdit = QtGui.QLineEdit(self.addressGroupBox)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.gridLayout_2.addWidget(self.cityLineEdit, 1, 1, 1, 1)
        self.deliveryLineEdit = QtGui.QLineEdit(self.addressGroupBox)
        self.deliveryLineEdit.setObjectName("deliveryLineEdit")
        self.gridLayout_2.addWidget(self.deliveryLineEdit, 0, 1, 1, 1)
        self.admLineEdit = QtGui.QLineEdit(self.addressGroupBox)
        self.admLineEdit.setObjectName("admLineEdit")
        self.gridLayout_2.addWidget(self.admLineEdit, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.addressGroupBox)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.addressGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.postalLineEdit = QtGui.QLineEdit(self.addressGroupBox)
        self.postalLineEdit.setObjectName("postalLineEdit")
        self.gridLayout_2.addWidget(self.postalLineEdit, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.addressGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.countryLineEdit = QtGui.QLineEdit(self.addressGroupBox)
        self.countryLineEdit.setObjectName("countryLineEdit")
        self.gridLayout_2.addWidget(self.countryLineEdit, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.addressGroupBox, 3, 0, 1, 2)
        self.phoneGroupBox = QtGui.QGroupBox(self.orgGroupBox)
        self.phoneGroupBox.setObjectName("phoneGroupBox")
        self.formLayout = QtGui.QFormLayout(self.phoneGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.voicePhoneLineEdit = QtGui.QLineEdit(self.phoneGroupBox)
        self.voicePhoneLineEdit.setObjectName("voicePhoneLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.voicePhoneLineEdit)
        self.label_6 = QtGui.QLabel(self.phoneGroupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.faxLineEdit = QtGui.QLineEdit(self.phoneGroupBox)
        self.faxLineEdit.setObjectName("faxLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.faxLineEdit)
        self.label_7 = QtGui.QLabel(self.phoneGroupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.gridLayout_3.addWidget(self.phoneGroupBox, 2, 0, 1, 2)
        self.emailLineEdit = QtGui.QLineEdit(self.orgGroupBox)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.gridLayout_3.addWidget(self.emailLineEdit, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.orgGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.contactGroupBox = QtGui.QGroupBox(self.orgGroupBox)
        self.contactGroupBox.setObjectName("contactGroupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.contactGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.contactTitleLineEdit = QtGui.QLineEdit(self.contactGroupBox)
        self.contactTitleLineEdit.setObjectName("contactTitleLineEdit")
        self.gridLayout_4.addWidget(self.contactTitleLineEdit, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.contactGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.contactPositionLineEdit = QtGui.QLineEdit(self.contactGroupBox)
        self.contactPositionLineEdit.setObjectName("contactPositionLineEdit")
        self.gridLayout_4.addWidget(self.contactPositionLineEdit, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.contactGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.hoursLineEdit = QtGui.QLineEdit(self.contactGroupBox)
        self.hoursLineEdit.setObjectName("hoursLineEdit")
        self.gridLayout_4.addWidget(self.hoursLineEdit, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.contactGroupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.contactGroupBox, 4, 0, 1, 2)
        self.gridLayout.addWidget(self.orgGroupBox, 2, 0, 1, 2)

        self.retranslateUi(OrganizationEditorDialog)
        QtCore.QObject.connect(self.orgButtonBox, QtCore.SIGNAL("accepted()"), OrganizationEditorDialog.accept)
        QtCore.QObject.connect(self.orgButtonBox, QtCore.SIGNAL("rejected()"), OrganizationEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OrganizationEditorDialog)

    def retranslateUi(self, OrganizationEditorDialog):
        OrganizationEditorDialog.setWindowTitle(QtGui.QApplication.translate("OrganizationEditorDialog", "Edit institution", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.orgGroupBox.setTitle(QtGui.QApplication.translate("OrganizationEditorDialog", "Institution", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.addressGroupBox.setTitle(QtGui.QApplication.translate("OrganizationEditorDialog", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "DeliveryPoint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Administrative area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Postal code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.phoneGroupBox.setTitle(QtGui.QApplication.translate("OrganizationEditorDialog", "Phone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Voice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Fax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.contactGroupBox.setTitle(QtGui.QApplication.translate("OrganizationEditorDialog", "Contact person", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Contact person title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Contact person position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("OrganizationEditorDialog", "Hours of service", None, QtGui.QApplication.UnicodeUTF8))

