# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_organization_editor.ui'
#
# Created: Wed Mar 30 16:35:56 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OrganisationsEditorDialog(object):
    def setupUi(self, OrganisationsEditorDialog):
        OrganisationsEditorDialog.setObjectName(_fromUtf8("OrganisationsEditorDialog"))
        OrganisationsEditorDialog.resize(440, 486)
        self.verticalLayout = QtGui.QVBoxLayout(OrganisationsEditorDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cmbOrganisation = QtGui.QComboBox(OrganisationsEditorDialog)
        self.cmbOrganisation.setObjectName(_fromUtf8("cmbOrganisation"))
        self.verticalLayout.addWidget(self.cmbOrganisation)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnNew = QtGui.QPushButton(OrganisationsEditorDialog)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.horizontalLayout.addWidget(self.btnNew)
        self.btnRemove = QtGui.QPushButton(OrganisationsEditorDialog)
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.horizontalLayout.addWidget(self.btnRemove)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtGui.QGroupBox(OrganisationsEditorDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.leName = QtGui.QLineEdit(self.groupBox)
        self.leName.setObjectName(_fromUtf8("leName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.leName)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.textAddress = QtGui.QTextEdit(self.groupBox)
        self.textAddress.setObjectName(_fromUtf8("textAddress"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textAddress)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lePhone = QtGui.QLineEdit(self.groupBox)
        self.lePhone.setObjectName(_fromUtf8("lePhone"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lePhone)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.leFax = QtGui.QLineEdit(self.groupBox)
        self.leFax.setObjectName(_fromUtf8("leFax"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.leFax)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.leEmail = QtGui.QLineEdit(self.groupBox)
        self.leEmail.setObjectName(_fromUtf8("leEmail"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.leEmail)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.leContactPerson = QtGui.QLineEdit(self.groupBox)
        self.leContactPerson.setObjectName(_fromUtf8("leContactPerson"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.leContactPerson)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lePersonTitle = QtGui.QLineEdit(self.groupBox)
        self.lePersonTitle.setObjectName(_fromUtf8("lePersonTitle"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lePersonTitle)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lePersonPosition = QtGui.QLineEdit(self.groupBox)
        self.lePersonPosition.setObjectName(_fromUtf8("lePersonPosition"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lePersonPosition)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.leOfficeHours = QtGui.QLineEdit(self.groupBox)
        self.leOfficeHours.setObjectName(_fromUtf8("leOfficeHours"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.leOfficeHours)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(OrganisationsEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OrganisationsEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), OrganisationsEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), OrganisationsEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OrganisationsEditorDialog)

    def retranslateUi(self, OrganisationsEditorDialog):
        OrganisationsEditorDialog.setWindowTitle(QtGui.QApplication.translate("OrganisationsEditorDialog", "Manage organisations", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemove.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("OrganisationsEditorDialog", "Organisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Telephone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Fax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "E-Mail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Contact person", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Person title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Person position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("OrganisationsEditorDialog", "Office hours", None, QtGui.QApplication.UnicodeUTF8))

